fplbhaktapur/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fplengine.urls')),
]

if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fplengine/urls.py
from .views import *
from django.conf.urls import url
from django.urls import include,path

app_name = 'cv'

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    path('teams', TeamView.as_view(), name='teams'),
    path('player/<int:pk>/', PlayerDetailsView.as_view(), name='player-detail'),
    path('division/<str:division>/', DivisionSelectionView.as_view(), name='divisionselection'),
    path('about',AboutView.as_view(),name='about'),
    path('rewards',RewardsView.as_view(),name='rewards'),
    path('rewards',RulesView.as_view(),name='rewards'),
    path('gameweekwinner',GameweekWinnerView.as_view(),name='gameweekwinner'),
    path('classicleague',ClassicLeagueView.as_view(),name='classicleague'),
    path('divisionleague',DivisionView.as_view(),name='divisionleague'),
    path('divisiongameweekwinner',DivisionGameWeekWinnerView.as_view(),name='divisiongameweekwinner'),
    path('eliminationleague',EliminationLeagueView.as_view(),name='eliminationleague'),
    path('iamsafe',IamSafeView.as_view(),name='iamsafe'),
    path('blogs',BlogsView.as_view(),name='blogs'),
    path('blog/',BlogsingleView.as_view(),name='blog'),
    path('rules',RulesView.as_view(),name='rules'),
    path('contact',ContactView.as_view(),name='contact'),


    path('home', get_home, name='fpl-home'),
    path('check-safe', check_iam_safe ,name="check-safe"),
    path('latest-gameweek-winner', get_gameweek_winner, name='gameweek-winner'),
]

templates/newtemplate/about.html
{% extends 'newtemplate/base.html' %} 
{% load static %} 
{% block style %} 
<link rel=stylesheet type=text/css href="{% static 'newtemplate/css/tablestyle.css' %}">
<style>
    .heading-2{
        font-size:12px !important; 
        text-align: left !important;
        margin-top: 20px;
        margin-bottom: 5px;
    }

    .ruledescription{
        margin-bottom: 30px !important;
        text-align: justify;
  text-justify: inter-word;
  text-indent: 50px;
    }
</style>
{% endblock %} 
{% block content %}

<section>
<div class="row">
    <div class="container">

  <div class="col">
    

    


  </div>
  </div>
</div>
</section>
{% endblock %}

templates/newtemplate/base.html
<!doctype html>
{% load static %}
<html class=no-js lang="">
<meta http-equiv="content-type" content="text/html;charset=utf-8"/>
<head>
    <meta charset=utf-8>
    <meta name=description content="">
    <meta name="viewport"
          content="width=device-width, height=device-height, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    

    
    <link rel="shortcut icon" href="{% static 'newtemplate/favicon.ico'%}">
    <link rel=stylesheet href="{% static 'newtemplate/css/vendor.css' %}">
    <link rel=stylesheet href="{% static 'newtemplate/css/style.css' %}">
    <link rel=stylesheet type=text/css href="{% static 'newtemplate/css/layerslider.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" />
    <link href="path/to/font-awesome/css/font-awesome.min.css">
    

    <script src="{% static 'newtemplate/js/vendor/modernizr.js' %}"></script>

    {% block style %}

{% endblock %}
</head>

<body id="bootstrap-overrides"><!--[if lt IE 10]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade
    your browser</a> to improve your experience.</p>
<![endif]-->

<div class=wrapper>
    <header class=header-main>
        {% comment %} <div class=header-upper>
            <div class=container>
                <div class=row>
                    <ul>
                        <li><a href="#">Signup/login</a></li>
                        <li><a href=shopcart.html><i class="fa fa-shopping-cart"></i> <span>cart(<span
                                class=cartitems>0</span>)</span></a></li>
                    </ul>
                </div>
            </div>
        </div> {% endcomment %}
        <div class="header-lower clearfix">
            <div class=container>
                <div class=row><h1 class=logo><a href="{% url 'cv:home' %}"><img src="{% static 'images/logo2.png' %}" alt=image></a></h1>

                    <div class=menubar>
                        <nav class=navbar>
                            <div class=nav-wrapper>
                                <div class=navbar-header>
                                    <button type=button class=navbar-toggle><span class=sr-only>Toggle navigation</span>
                                        <span class=icon-bar></span></button>
                                </div>
                                <div class=nav-menu>
                                    <ul class="nav navbar-nav menu-bar">
                                        <li><a href="{% url 'cv:home' %}" class=active>Home <span></span> <span></span>
                                            <span></span> <span></span></a></li>
                                        <li><a href="{% url 'cv:teams' %}">Teams <span></span> <span></span> <span></span>
                                            <span></span></a></li>
                                        <li><a>Game Mods<span></span> <span></span> <span></span> <span></span></a>
                                            <ul class=sub-menu>
                                                <li><a href="{% url 'cv:classicleague' %}">Classic League</a></li>
                                                <li><a href="{% url 'cv:gameweekwinner' %}">Gameweek Winner</a></li>
                                                <li><a href="{% url 'cv:divisionleague' %}">Division League</a></li>
                                                <!-- <li><a href="{% url 'cv:divisiongameweekwinner' %}">Division Gameweek Winner</a></li> -->
                                                <!-- <li><a href="{% url 'cv:eliminationleague' %}">Elimination League</a></li> -->
                                                <li><a href="{% url 'cv:iamsafe' %}">I am Safe</a></li>
                                            </ul>
                                        </li>
                                        <li><a href="{% url 'cv:rewards' %}">Rewards <span></span> <span></span> <span></span>
                                            <span></span></a></li>
                                        <li><a href="{% url 'cv:rules' %}">Rules  <span></span> <span></span>
                                            <span></span> <span></span></a></li>
                                        <!-- <li><a href="{% url 'cv:about' %}">About  <span></span> <span></span>
                                            <span></span> <span></span></a></li> -->
                                        <li><a href="{% url 'cv:contact' %}">contact <span></span> <span></span> <span></span>
                                            <span></span></a></li>
                                        <!-- <li><a>error <span></span> <span></span> <span></span> <span></span></a>
                                            <ul class=sub-menu>
                                                <li><a href=400.html>400 page</a></li>
                                                <li><a href=401.html>401 page</a></li>
                                                <li><a href=403.html>403 page</a></li>
                                                <li><a href=404.html>404 page</a></li>
                                                <li><a href=500.html>500 page</a></li>
                                                <li><a href=503.html>503 page</a></li>
                                            </ul>
                                        </li> -->
                                    </ul>
                                </div>
                            </div>
                        </nav>
                    </div>
                    <!-- <div class=social><a href="{{ company.fb_link }}" class=facebook><i
                            class="fa fa-plus-circle"></i></a> <a href=https://twitter.com/itobuztech class=twitter><i
                            class="fa fa-twitter"></i></a> <a href=https://www.behance.net/ class=behance><i
                            class="fa fa-behance"></i></a></div>
                </div> -->
            </div>
        </div>
    </header>
    {% block content %}
    {% endblock %}


  <footer class=footer-type01>
        <div class=container>
            <div class=row>
                <ul class=footer-widget>
                    <li class=widget-about><h4 class=footerheading>about <span>soccer club</span></h4>

                        <p>{{ company.description }}</p>

                        <p><span class=uppercaseheading>address:</span> {{ company.address }}</p>

                        <p><span class=uppercaseheading>call:</span> <span class=red>{{ company.phone_no }}</span></p></li>
                    <li class=widget-news><h4 class=footerheading>recent <span>news</span></h4>
                        <!-- <ul class="widget-newsdetails clearfix">
                            <li class=clearfix><a href="#" class=clearfix>
                                <div class=widget-pic
                                     style="background:url(images/widget/widget01.jpg) center no-repeat"></div>
                                <div class=widget-newsinfo><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                                    Numquam soluta excepturi.</p>

                                    <p class=uppercaseheading>18 september ,<span class=red>2015</span></p></div>
                            </a></li>
                            <li class=clearfix><a href="#" class=clearfix>
                                <div class=widget-pic
                                     style="background:url({% static 'newtemplate/images/widget/widget02.jpg' %}) center no-repeat"></div>
                                <div class=widget-newsinfo><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                                    Numquam soluta excepturi.</p>

                                    <p class=uppercaseheading>18 september ,<span class=red>2015</span></p></div>
                            </a></li>
                            <li class=clearfix><a href="#" class=clearfix>
                                <div class=widget-pic
                                     style="background:url(images/widget/widget03.jpg) center no-repeat"></div>
                                <div class=widget-newsinfo><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                                    Numquam soluta excepturi.</p>

                                    <p class=uppercaseheading>18 september ,<span class=red>2015</span></p></div>
                            </a></li>
                        </ul> -->
                    </li>
                    <!-- <li class=widget-product><h4 class=footerheading>real <span>soccer products</span></h4>
                        <ul class=widget_productdetails>
                            <li><a href=#>shoes(4)</a></li>
                            <li><a href=#>men(4)</a></li>
                            <li><a href=#>t-shirt(4)</a></li>
                            <li><a href=#>sports(4)</a></li>
                            <li><a href="#">glass</a></li>
                        </ul>
                    </li> -->
                    <!-- <li class=widget-comment><h4 class=footerheading>recent <span>comments</span></h4>
                        <ul class=widget_commentDetails>
                            <li><a href=# class=clearfix>
                                <div class=comment-pic>
                                    <div class=columnpic><img src="{% static 'newtemplate/images/widget/comment01.jpg' %}" alt=image></div>
                                </div>
                                <div class=commentinfo><p class=uppercaseheading>jhon doe</p>

                                    <p>18 April ,<span class=red>2015</span></p>

                                    <p>nice and cool</p></div>
                            </a></li>
                            <li><a href=# class=clearfix>
                                <div class=comment-pic>
                                    <div class=columnpic><img src="{% static 'newtemplate/images/widget/comment02.jpg' %}" alt=image></div>
                                </div>
                                <div class=commentinfo><p class=uppercaseheading>jhon doe</p>

                                    <p>18 April ,<span class=red>2015</span></p>

                                    <p>nice and cool</p></div>
                            </a></li>
                            <li><a href=# class=clearfix>
                                <div class=comment-pic>
                                    <div class=columnpic><img src="{% static 'newtemplate/images/widget/comment03.jpg' %}"alt=image></div>
                                </div>
                                <div class=commentinfo><p class=uppercaseheading>jhon doe</p>

                                    <p>18 April ,<span class=red>2015</span></p>

                                    <p>nice and cool</p></div>
                            </a></li> -->
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
        <div class=footer-type02>
            <div class=container>
                <div class=row><a href=index-2.html class=footer-logo><img src="{% static 'images/logo1.jpg' %}" alt=image></a>

                    <!-- <div class=footer-container>
                        <ul class=clearfix>
                            <li><a href=https://www.facebook.com/templatespoint.net class=bigsocial-link><i
                                    class="fa fa-facebook"></i></a></li>
                            <li><a href=https://twitter.com/ class=bigsocial-link target=_blank><i
                                    class="fa fa-twitter"></i></a></li>
                            <li><a href=https://www.behance.net/ class=bigsocial-link target=_blank><i
                                    class="fa fa-behance"></i></a></li>
                        </ul>
                        </div> -->
                    <!-- <div class=footer-appstore>
                        <figure><a href=#><img src="{% static 'newtemplate/images/appstore/apple.png' %}" alt=image></a></figure>
                        <figure><a href=#><img src="{% static 'newtemplate/images/appstore/google.png' %}" alt=image></a></figure>
                    </div> -->
                </div>
            </div>
        </div>
    </footer>

    
</div>

<script src="{% static 'newtemplate/js/vendor/vendor.js' %}"></script>
<script src="{% static 'newtemplate/js/main.js' %}"></script>
{% block script %}
{% endblock%}
</body>

</html>

templates/newtemplate/classicleague.html
{% extends 'newtemplate/base.html' %}
{% load static %}
{% block style %}
<link rel=stylesheet type=text/css href="{% static 'newtemplate/css/tablestyle.css' %}">
 {% endblock %} 
 
{% block content %}
<section>

    <!--for demo wrap-->
    <h2 class=heading><span> Classic</span>League</h2>

  </section> 
  
    <div style="margin-top: 20px;;" class="tbl-header">
      <table cellpadding="0" cellspacing="0" border="0">
        <thead>
          <tr>
            {% comment %} <th>SN</th> {% endcomment %}
            <th>Position</th>
            <th>Manager</th>
            <th>Points</th>
            <th>Total Point</th>
          </tr>
        </thead>
      </table>
    </div>
    <div class="tbl-content">
      <table cellpadding="0" cellspacing="0" border="0">
        <tbody>
            {% for obj in object_list %}
            <tr>
                <td>{{ obj.position }}</td>
                <td><a style="color: #dbc570;" href="{% url 'cv:player-detail' pk=obj.name.pk %}">{{ obj.name.name }},<br>{{obj.name.teamname}}</a></td>
                <td>{{ obj.event_total }}</td>
                <td>{{ obj.total_points }}</td>
              </tr>
           {% endfor %}
          
        </tbody>
      </table>
    </div>




  {% endblock %}
{% block script %}
<script>
// '.tbl-content' consumed little space for vertical scrollbar, scrollbar width depend on browser/os/platfrom. Here calculate the scollbar width .
$(window).on("load resize ", function() {
  var scrollWidth = $('.tbl-content').width() - $('.tbl-content table').width();
  $('.tbl-header').css({'padding-right':scrollWidth});
}).resize();
</script>
{% endblock %}

templates/newtemplate/division.html
{% extends 'newtemplate/base.html' %}
{% load static %}
{% block style %}
<link rel=stylesheet type=text/css href="{% static 'newtemplate/css/tablestyle.css' %}">
  <style>

    /* custom */
.nav-link{
  text-align: center;
  color: #b81e20 !important;
  font-weight: bold;
  font-family: "Oswald", sans-serif;
}
  </style>
 {% endblock %} 
 
{% block content %}
<section>

  
    <!--for demo wrap-->
    <h2 class="heading"><span> Division</span>League</h2>
    <div class="row" style="margin-bottom: 30;">
 
      <div class="container">
        <div class="dynamic-tabs">
          <ul class="nav nav-tabs justify-content-between">
            <li class="nav-item" style="flex: 1">
              <a class="nav-link active" data-toggle="pill" href="#">All Divisions</a>
            </li>
            <li class="nav-item" style="flex: 1">
              <a class="nav-link" href="{% url 'cv:divisionselection' division='A' %}">Division A</a>
            </li>
            <li class="nav-item" style="flex: 1">
              <a class="nav-link" data-toggle="pill" href="#B">Division B</a>
            </li>
          </ul>
        </div>

        <div class="col-lg-6">
          <h2 style="font-size: 16px; 
          margin-top: 20px; " class="heading heading2" >Division<span> A</span></h2>
          <div style="margin-top: 20px;;" class="tbl-header">
            <table cellpadding="0" cellspacing="0" border="0">
              <thead>
                <tr> 
                  <th>Position</th>
                  <th>Manager</th>
                  <th>Points</th>
                  <th>Total Point</th>
                  <!-- <th>Action</th> -->
                </tr>
              </thead>
            </table>
          </div>
          <div class="tbl-content">
            <table cellpadding="0" cellspacing="0" border="0">
              <tbody>
          {% for obj in teama %}
          <tr>
              <td>{{ obj.position }}</td>
              <td><a style="color: #dbc570;"  href="{% url 'cv:player-detail' pk=obj.name.pk %}"><br>{{obj.name.teamname}}</a></td>
              <td>{{ obj.event_total }}</td>
              <td>{{ obj.total_points }}</td>
             
            </tr>
        {% endfor %}
          
        </tbody>
      </table>
    </div>
      </div>

      <div class="col-lg-6">
        <h2 style="font-size: 16px; 
        margin-top: 20px;" class="heading">Division<span> B</span></h2>
        <div style="margin-top: 20px;" class="tbl-header">
          <table cellpadding="0" cellspacing="0" border="0">
            <thead>
              <tr> 
                <th>Position</th>
                <th>Manager</th>
                <th>Points</th>
                <th>Total Point</th>
                <!-- <th>Action</th> -->
              </tr>
            </thead>
          </table>
        </div>
        <div class="tbl-content">
          <table cellpadding="0" cellspacing="0" border="0">
            <tbody>
        {% for obj in teamb %}
        <tr>
            <td>{{ obj.position }}</td>
            <td><a style="color: #dbc570;" href="{% url 'cv:player-detail' pk=obj.name.pk %}">{{ obj.name.name }},<br>{{obj.name.teamname}}</a></td>
            <td>{{ obj.event_total }}</td>
            <td>{{ obj.total_points }}</td>
            <!-- <td><a style="color: #dbc570;">Details</a></td> -->
          </tr>
      {% endfor %}
        
      </tbody>
    </table>
  </div>
    </div>

  </div>
  </section>
  
  
  <!-- follow me template -->
  <!-- <div class="made-with-love">
    Made with
    <i>♥</i> by
    <a target="_blank" href="https://codepen.io/nikhil8krishnan">Nikhil Krishnan</a>
  </div> -->



  {% endblock %}
{% block script %}
<script>
// '.tbl-content' consumed little space for vertical scrollbar, scrollbar width depend on browser/os/platfrom. Here calculate the scollbar width .
$(window).on("load resize ", function() {
  var scrollWidth = $('.tbl-content').width() - $('.tbl-content table').width();
  $('.tbl-header').css({'padding-right':scrollWidth});
}).resize();
</script>
{% endblock %}


templates/newtemplate/gameweekwinner.html
{% extends 'newtemplate/base.html' %}
{% load static %}
{% block style %}
<link rel=stylesheet type=text/css href="{% static 'newtemplate/css/tablestyle.css' %}">
 {% endblock %} 
 
{% block content %}
<section>
  <h2 class=heading><span>Gameweek </span>Winner</h2>
  </section>
    <!--for demo wrap-->
    <div class="table-main" style="padding: 0 10px 10px 10px">
    <div style="margin-top: 20px;;" class="tbl-header">
      <table cellpadding="0" cellspacing="0" border="0">
        <thead>
          <tr>
            {% comment %} <th>SN</th> {% endcomment %}
            <th width="20px">GW</th>
            <th>Manager</th>
            <th>Points</th>
          </tr>
        </thead>
      </table>
    </div>
    <div class="tbl-content">
      <table cellpadding="0" cellspacing="0" border="0">
        <tbody>
            {% for winner in gwwinner %}
            <tr>
                <td width="20px">{{ winner.gameweek }}</td>
                <td>{% for w in winner.name.all %}
                  <a style="color: #dbc570;" href="{% url 'cv:player-detail' pk=w.pk %}">
                  {{ w.name }}
                  {% endfor %}
                </a></td>
                <td>{{ winner.points }}</td>
                {% comment %} <td>{{ team.name }}</td> {% endcomment %}
              </tr>
           {% endfor %}
          
        </tbody>
      </table>
    </div>
</div>
  


  {% endblock %}
{% block script %}
<script>
// '.tbl-content' consumed little space for vertical scrollbar, scrollbar width depend on browser/os/platfrom. Here calculate the scollbar width .
$(window).on("load resize ", function() {
  var scrollWidth = $('.tbl-content').width() - $('.tbl-content table').width();
  $('.tbl-header').css({'padding-right':scrollWidth});
}).resize();
</script>
{% endblock %}

templates/newtemplate/iamsafe.html
{% extends 'newtemplate/base.html' %} 
{% load static %} 
{% block style %} 
<link rel=stylesheet type=text/css href="{% static 'newtemplate/css/tablestyle.css'%}"> 
{% comment %}
<link rel="stylesheet" href="{% static 'newtemplate/css/bootstrap.css' %}" /> 
{% endcomment %} 
{% endblock %} 
{% block content %}
<section
  class="list-category section-margin-top-bottom"
  style="margin-top: 100px"
>
  <div class="container">
    <div class="dynamic-tabs">
      <ul class="nav nav-tabs justify-content-between">
        <li class="nav-item" style="flex: 1">
          <a class="nav-link active" data-toggle="pill" href="#A">All Detail</a>
        </li>
        <li class="nav-item" style="flex: 1">
          <a class="nav-link" data-toggle="pill" href="#B">Safe</a>
        </li>
        <li class="nav-item" style="flex: 1">
          <a class="nav-link" data-toggle="pill" href="#C"> Un Safe</a>
        </li>
      </ul>
    </div>

    <div class="section-content mt-4">
      <div class="tab-content">
        <div class="tab-pane active" id="A">
          <table cellpadding="0" cellspacing="0" border="0">
            <thead>
              <tr>
                <th>SN</th>

                <th>Team</th>
                <th>Manager</th>
                <th>Gameweek</th>
                <th>Gameweek point</th>
              </tr>
            </thead>
          </table>
        </div>
        <div class="tbl-content">
          <table cellpadding="0" cellspacing="0" border="0">
            <tbody>
              {% for team in object_list%}
              <tr>
                <td>{{ team.id }}</td>
                <td>
                  <a
                    style="color: #dbc570"
                    href="{% url 'cv:player-detail' pk=team.pk %}"
                    >{{ team.name.name }}</a
                  >
                </td>
                <td>{{ team.name.teamname }}</td>
                <td>{{ team.name.eliminated_gameweek }}</td>
                <td>
                  <a
                    style="font-weight: bold; color: #dbc570"
                    href="{% url 'cv:player-detail' pk=team.pk %}"
                    >{{team.name.issafe}}</a
                  >
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>

        <div class="tab-pane" id="B">
        <table cellpadding="0" cellspacing="0" border="0">
        <thead>
          <tr>
            <th>SN</th>
            
            <th>Team</th>
            <th>Manager</th>
            <th>Gameweek</th>
            <th>Gameweek point</th>
          </tr>
        </thead>
      </table>
    </div>
    <div class="tbl-content">
      <table cellpadding="0" cellspacing="0" border="0">
        <tbody>
            {% for team in object_list%}
            <tr>
                <td>{{ team.id }}</td>
                <td><a style="color: #dbc570;" href="{% url 'cv:player-detail' pk=team.pk %}">{{ team.name.name }}</a></td>
                <td>{{ team.name.teamname }}</td>
                <td>{{ team.name.eliminated_gameweek }}</td>
                <td><a style="font-weight:bold; color: #dbc570;" href="{% url 'cv:player-detail' pk=team.pk %}">{{team.name.issafe}}</a></td>
              </tr>
           {% endfor %}
          
        </tbody>
      </table>
        </div>

        <div class="tab-pane" id="C">
          <table cellpadding="0" cellspacing="0" border="0">
            <thead>
              <tr>
                <th>SN</th>

                <th>Team</th>
                <th>Manager</th>
                <th>Gameweek</th>
                <th>Gameweek point</th>
              </tr>
            </thead>
          </table>
        </div>
        <div class="tbl-content">
          <table cellpadding="0" cellspacing="0" border="0">
            <tbody>
              {% for team in unsafe_team%}
              <tr>
                <td>{{ team.id }}</td>
                <td>
                  <a
                    style="color: #dbc570"
                    href="{% url 'cv:player-detail' pk=team.pk %}"
                    >{{ team.name.name }}</a
                  >
                </td>
                <td>{{ team.name.teamname }}</td>
                <td>{{ team.name.eliminated_gameweek }}</td>
                <td>
                  <a
                    style="font-weight: bold; color: #dbc570"
                    href="{% url 'cv:player-detail' pk=team.pk %}"
                    >{{team.name.issafe}}</a
                  >
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</section>
{% comment %}
<section>
  <!--for demo wrap-->
  <h2 class="heading">FPL Bhaktapur <span>Teams</span></h2>
  <div style="margin-top: 20px ;" class="tbl-header">
    <table cellpadding="0" cellspacing="0" border="0">
      <thead>
        <tr>
          <th>SN</th>
          <th>Entry</th>
          <th>Team</th>
          <th>Manager</th>
          <th></th>
        </tr>
      </thead>
    </table>
  </div>
  <div class="tbl-content">
    <table cellpadding="0" cellspacing="0" border="0">
      <tbody>
        {% for team in teams%}
        <tr>
          <td>{{ team.id }}</td>
          <td>
            <a
              style="color: #dbc570"
              href="{% url 'cv:player-detail' pk=team.pk %}"
              >{{ team.entry }}</a
            >
          </td>
          <td>{{ team.teamname }}</td>
          <td>{{ team.name }}</td>
          <td>
            <a
              style="font-weight: bold; color: #dbc570"
              href="{% url 'cv:player-detail' pk=team.pk %}"
              >Details</a
            >
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</section>
{% endcomment %}

{% endblock %} {% block script %}
<script>
  // '.tbl-content' consumed little space for vertical scrollbar, scrollbar width depend on browser/os/platfrom. Here calculate the scollbar width .
  $(window)
    .on("load resize ", function () {
      var scrollWidth =
        $(".tbl-content").width() - $(".tbl-content table").width();
      $(".tbl-header").css({ "padding-right": scrollWidth });
    })
    .resize();
</script>
{% endblock %}

templates/newtemplate/rewards.html
{% extends 'newtemplate/base.html' %} 
{% load static %} 
{% block style %} 
<link rel=stylesheet type=text/css href="{% static 'newtemplate/css/tablestyle.css' %}">
{% endblock %} 
{% block content %}


<section>
  <div class="row">
    <div class="container">

  <div class="col">
  <h2 style=" margin-top:40px; margin-bottom:40px;" class="heading"> <span>Rewards</span></span></h2>
      <img class="rewardimage" src="{{company.rewards.url}}" alt="reward-image" width=100% height=850px>
    </div>
    </div>
  </div>

    </section>
    {% endblock %}     

templates/newtemplate/teams.html
{% extends 'newtemplate/base.html' %}
{% load static %}
{% block style %}
<link rel=stylesheet type=text/css href="{% static 'newtemplate/css/tablestyle.css' %}">
 {% endblock %} 
 
{% block content %}
<section>

    <!--for demo wrap-->
    <h2 class=heading>FPL Bhaktapur <span>Teams</span></h2>

  </section>
  
<div class="table-main" style="padding: 0 5px 5px 5px">
  <div class="tbl-header">
    <table cellpadding="0" cellspacing="0" border="0">
      <thead>
        <tr>
          <th width="20px">SN</th>
          <th>Team Name</th>
          <th>Manager</th>
        </tr>
      </thead>
    </table>
  </div>
  <div class="tbl-content">
    <table cellpadding="0" cellspacing="0" border="0">
      <tbody>
          {% for team in teams%}
          <tr>
              <td width=20px;>{{ team.id }}</td>
              <td><a style="color: #dbc570;" href="{% url 'cv:player-detail' pk=team.pk %}">{{ team.teamname }}</a></td>
              <td>{{ team.name }}</td>
            </tr>
         {% endfor %}
        
      </tbody>
    </table>
  </div>
</div>
  <!-- follow me template -->
  <!-- <div class="made-with-love">
    Made with
    <i>♥</i> by
    <a target="_blank" href="https://codepen.io/nikhil8krishnan">Nikhil Krishnan</a>
  </div> -->



  {% endblock %}
{% block script %}
<script>
// '.tbl-content' consumed little space for vertical scrollbar, scrollbar width depend on browser/os/platfrom. Here calculate the scollbar width .
$(window).on("load resize ", function() {
  var scrollWidth = $('.tbl-content').width() - $('.tbl-content table').width();
  $('.tbl-header').css({'padding-right':scrollWidth});
}).resize();
</script>
{% endblock %}
